# Generated by Django 4.2.7 on 2023-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_name',
            field=models.CharField(choices=[('equity_bank', 'Equity Bank'), ('bk', 'BK'), ('ecobank', 'Ecobank')], max_length=255),
        ),
        migrations.AlterField(
            model_name='moneytransfertransaction',
            name='company',
            field=models.CharField(choices=[('western_union', 'Western Union'), ('moneygram', 'MoneyGram'), ('mpesa', 'M-Pesa'), ('dubai', 'Dubai')], max_length=20),
        ),
    ]
